# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountRetailApp', '0002_blog_entry_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='empty content', max_length=1000, verbose_name='\u5185\u5bb9'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='empty title', max_length=256, verbose_name='\u6807\u9898'),
        ),
    ]
