# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountRetailApp', '0003_auto_20171003_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='auth',
            field=models.CharField(default='no author', max_length=30, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='\u90ae\u4ef6'),
        ),
    ]
