# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountRetailApp', '0004_auto_20171003_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
        migrations.AlterField(
            model_name='blog',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1'),
        ),
    ]
