# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountRetailApp', '0010_auto_20171011_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(default='no address', max_length=30, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u59d3\u540d'),
        ),
    ]
