# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountRetailApp', '0011_auto_20171011_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.IntegerField(auto_created=True)),
                ('categoryName', models.CharField(max_length=30)),
                ('categoryIntro', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumerid', models.IntegerField(auto_created=True)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.CharField(default='', max_length=100)),
                ('tel', models.CharField(default='', max_length=14)),
                ('logo', models.CharField(default='', max_length=200)),
                ('consumer_intro', models.CharField(max_length=20)),
                ('register_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_create_time', models.DateTimeField()),
                ('orer_complete_time', models.DateTimeField()),
                ('order_close_time', models.DateTimeField()),
                ('consumerid', models.IntegerField()),
                ('sellerid', models.IntegerField()),
                ('wareid', models.IntegerField()),
                ('order_price', models.CharField(max_length=20)),
                ('order_comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='sellerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerid', models.IntegerField(auto_created=True)),
                ('sellname', models.CharField(max_length=30)),
                ('sellerOwnerName', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('tel', models.CharField(default='', max_length=14)),
                ('seller_logo', models.CharField(default='', max_length=200)),
                ('seller_intro', models.CharField(max_length=500)),
                ('lat', models.CharField(max_length=20)),
                ('log', models.CharField(max_length=20)),
                ('commit_apply_time', models.DateTimeField()),
                ('start_bussiness_time', models.DateTimeField()),
                ('close_bussiness_time', models.DateTimeField()),
                ('isInBussiness', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='waresInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wareId', models.IntegerField(auto_created=True)),
                ('ware_img', models.CharField(max_length=200)),
                ('ware_video_url', models.CharField(max_length=200)),
                ('wareIntro', models.CharField(max_length=500)),
                ('warePrice', models.CharField(max_length=20)),
                ('sellerId', models.IntegerField()),
                ('on_sail_time', models.DateTimeField()),
                ('init_sail_count', models.IntegerField(default=0)),
                ('current_available_count', models.IntegerField(default=0)),
                ('wareCategoryId', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
