# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-12 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountRetailApp', '0012_auto_20171011_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerinfo',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sellerinfo',
            name='start_bussiness_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='waresinfo',
            name='on_sail_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
